# Generated by Django 4.2.1 on 2023-05-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSomeWords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='words',
            new_name='word',
        ),
    ]
