# Generated by Django 4.2.1 on 2023-05-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=64)),
                ('translation', models.CharField(max_length=64)),
                ('chosen', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
    ]
