# Generated by Django 4.2.1 on 2023-05-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnSomeWords', '0002_rename_words_words_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('pos', models.CharField(max_length=8)),
                ('translation', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('sentences', models.JSONField()),
                ('chosen', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Words',
        ),
    ]
